language: cpp
compiler:
  - gcc
# - clang
before_install:
  - curl http://download.opensuse.org/repositories/home:/wojdyr/xUbuntu_12.04/Release.key | sudo apt-key add -
  - echo 'deb http://download.opensuse.org/repositories/home:/wojdyr/xUbuntu_12.04/ /' | sudo tee -a /etc/apt/sources.list.d/obs.list
  - sudo add-apt-repository ppa:teward/swig3.0 -y
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost-dev liblua5.1-0-dev lua5.1 libgtk2.0-dev
  - sudo apt-get install -y --force-yes swig3.0
  - sudo apt-get install -y --force-yes libxy-dev wxgtk-for-fityk-devel
before_script:
  -  curl -o tests/catch.hpp https://github.com/philsquared/Catch/releases/download/v1.10.0/catch.hpp
  - autoreconf -i
script: ./configure LUA=/usr/bin/lua5.1 LUA_INCLUDE=-I/usr/include/lua5.1 LUA_LIB=-llua5.1 SWIG=swig3.0 && make -j2 check

branches:
  only:
    - master

notifications:
  email:
    - wojdyr@gmail.com
